/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Julian Martinez <juli450@gmail.com>
 */
public class Desktop extends javax.swing.JFrame {
    entidades.Directorio d1;
    /**
     * Creates new form Desktop
     */
    public Desktop() {
        initComponents();
    }
    public Desktop(entidades.Directorio dir) {
        d1 = dir;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MCliente = new javax.swing.JMenu();
        MNuevoCliente = new javax.swing.JMenuItem();
        MBorrarCliente = new javax.swing.JMenuItem();
        MBusquedaCliente = new javax.swing.JMenuItem();
        MSistema = new javax.swing.JMenu();
        MSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        MCliente.setText("Cliente");

        MNuevoCliente.setText("Nuevo Cliente");
        MNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNuevoClienteActionPerformed(evt);
            }
        });
        MCliente.add(MNuevoCliente);

        MBorrarCliente.setText("Borrar Clientes");
        MBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBorrarClienteActionPerformed(evt);
            }
        });
        MCliente.add(MBorrarCliente);

        MBusquedaCliente.setText("Busqueda Cliente");
        MBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBusquedaClienteActionPerformed(evt);
            }
        });
        MCliente.add(MBusquedaCliente);

        jMenuBar1.add(MCliente);

        MSistema.setText("Sistema");

        MSalir.setText("Salir del sistema");
        MSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSalirActionPerformed(evt);
            }
        });
        MSistema.add(MSalir);

        jMenuBar1.add(MSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBusquedaClienteActionPerformed
        BusquedaClientes Bc = new BusquedaClientes(d1) ;
        Escritorio.removeAll();
        Escritorio.repaint();
        Escritorio.add(Bc);
        Escritorio.moveToFront(Bc);
        Bc.setVisible(true);
    }//GEN-LAST:event_MBusquedaClienteActionPerformed

    private void MBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBorrarClienteActionPerformed
        BorrarClientes Bc = new BorrarClientes(d1) ;
        Escritorio.removeAll();
        Escritorio.repaint();
        Escritorio.add(Bc);
        Escritorio.moveToFront(Bc);
        Bc.setVisible(true);
    }//GEN-LAST:event_MBorrarClienteActionPerformed

    private void MNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNuevoClienteActionPerformed
        FormularioDeClientes Bc = new FormularioDeClientes(d1) ;
        Escritorio.removeAll();
        Escritorio.repaint();
        Escritorio.add(Bc);
        Escritorio.moveToFront(Bc);
        Bc.setVisible(true);
    }//GEN-LAST:event_MNuevoClienteActionPerformed

    private void MSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSalirActionPerformed
        dispose();
    }//GEN-LAST:event_MSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main2() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MBorrarCliente;
    private javax.swing.JMenuItem MBusquedaCliente;
    private javax.swing.JMenu MCliente;
    private javax.swing.JMenuItem MNuevoCliente;
    private javax.swing.JMenuItem MSalir;
    private javax.swing.JMenu MSistema;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
